PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX besluitvorming: <http://data.vlaanderen.be/ns/besluitvorming#>
PREFIX eli: <http://data.europa.eu/eli/ontology#>

DELETE {
  GRAPH # GRAPH_PLACEHOLDER {
    ?decision a besluit:Besluit .
    ?decision ext:beslissingsfiche ?bf .
    ?decision eli:title_short ?tit . # unused
    ?decision ext:htmlInhoud ?content . # unused
    ?decision besluitvorming:gearchiveerd ?arch . # unused
    ?decision besluitvorming:stuknummerVP ?svp . # unused
    ?decision besluitvorming:stuknummerVR ?svr . # unused
  }
}
INSERT {
  GRAPH # GRAPH_PLACEHOLDER {
    ?decision a besluit:BehandelingVanAgendapunt ;
       besluitvorming:genereertVerslag ?bf .
  }
}
WHERE {
  GRAPH # GRAPH_PLACEHOLDER {
    ?decision a besluit:Besluit .
    OPTIONAL { ?decision ext:beslissingsfiche ?bf }
    OPTIONAL { ?decision eli:title_short ?tit }
    OPTIONAL { ?decision besluitvorming:gearchiveerd ?arch }
    OPTIONAL { ?decision besluitvorming:stuknummerVP ?svp }
    OPTIONAL { ?decision besluitvorming:stuknummerVR ?svr }
  }
  VALUES ?decision {
    # VALUES_PLACEHOLDER
  }
}
