PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX besluitvorming: <http://data.vlaanderen.be/ns/besluitvorming#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dbpedia: <http://dbpedia.org/ontology/>

INSERT {
  GRAPH # GRAPH_PLACEHOLDER {
    ?treatment besluitvorming:vindtPlaatsTijdens ?subcase .
  }
}
WHERE {
  GRAPH # GRAPH_PLACEHOLDER {
    ?agendaItem a besluit:Agendapunt .
    ?subcase besluitvorming:isGeagendeerdVia ?agendaItem .
    ?subcase a dbpedia:UnitOfWork .
    ?treatment besluitvorming:heeftOnderwerp ?agendaItem .
  }
}