PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX besluitvorming: <http://data.vlaanderen.be/ns/besluitvorming#>
PREFIX dbpedia: <http://dbpedia.org/ontology/>

INSERT {
  GRAPH # GRAPH_PLACEHOLDER {
    ?treatment besluitvorming:beslissingVindtPlaatsTijdens ?subcase .
  }
}
WHERE {
  GRAPH # GRAPH_PLACEHOLDER {
    ?agendaItem a besluit:Agendapunt .
    ?subcase a dbpedia:UnitOfWork .
    ?agendering a besluitvorming:Agendering ;
      besluitvorming:vindtPlaatsTijdens ?subcase ;
      besluitvorming:genereertAgendapunt ?agendaItem .
    ?treatment a besluit:BehandelingVanAgendapunt ;
      besluitvorming:heeftOnderwerp ?agendaItem .
  }
}